# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage_override.buildID", "20110622105328");
user_pref("browser.startup.homepage_override.mstone", "rv:5.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "{5fa014b6-c474-4c5d-8b0e-c1e73cbefbc4}:2.1,{451500c0-902c-11e0-91e4-0800200c9a66}:3.0");
user_pref("extensions.forcertl.rtl", true);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox-5/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1309236214000}}},{\"name\":\"app-profile\",\"addons\":{\"{5fa014b6-c474-4c5d-8b0e-c1e73cbefbc4}\":{\"descriptor\":\"/home/leighton/firefox/adwaita-firefox/testprof.RTL/extensions/{5fa014b6-c474-4c5d-8b0e-c1e73cbefbc4}.xpi\",\"mtime\":1309515692000},\"{451500c0-902c-11e0-91e4-0800200c9a66}\":{\"descriptor\":\"/home/leighton/firefox/adwaita-firefox/testprof.RTL/extensions/{451500c0-902c-11e0-91e4-0800200c9a66}.xpi\",\"mtime\":1309515570000}}}]");
user_pref("extensions.lastAppVersion", "5.0");
user_pref("extensions.pendingOperations", false);
user_pref("general.skins.selectedSkin", "Adwaita");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("intl.uidirection.en-US", "rtl");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 94832);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1312107391);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
